[build]
publish = "netlify-site"
functions = "netlify-functions"
command = "echo 'No build step required'"

[build.environment]
DB_HOST = "localhost"
DB_USER = "user43104"
DB_PASS = "4wJVPki5EPnA"
DB_NAME = "user43104"
