<?php

if (!defined('TABLE_ACCOUNTS')) define('TABLE_ACCOUNTS', 'accounts');
if (!defined('TABLE_ID')) define('TABLE_ID', 'ID');
if (!defined('TABLE_NAME')) define('TABLE_NAME', 'Name');
if (!defined('TABLE_PASSWORD')) define('TABLE_PASSWORD', 'Password');
if (!defined('TABLE_MONEY')) define('TABLE_MONEY', 'Money');
if (!defined('TABLE_LASTDATE')) define('TABLE_LASTDATE', 'LastData');
if (!defined('TABLE_LASTIP')) define('TABLE_LASTIP', 'LastIP');
if (!defined('TABLE_PHONE')) define('TABLE_PHONE', 'Number');
if (!defined('TABLE_BUSINESS')) define('TABLE_BUSINESS', 'Business');
if (!defined('TABLE_HOUSE')) define('TABLE_HOUSE', 'House');
if (!defined('TABLE_LEVEL')) define('TABLE_LEVEL', 'Level');
if (!defined('TABLE_BANK')) define('TABLE_BANK', 'Bank');
if (!defined('TABLE_MEMBER')) define('TABLE_MEMBER', 'Member');
if (!defined('TABLE_RANK')) define('TABLE_RANK', 'Rank');
if (!defined('TABLE_JOB')) define('TABLE_JOB', 'Job');
if (!defined('TABLE_WARN')) define('TABLE_WARN', 'Warn');
if (!defined('TABLE_DONATE')) define('TABLE_DONATE', 'Donate');
if (!defined('TABLE_SKIN')) define('TABLE_SKIN', 'Skin');
if (!defined('TABLE_ONLINE')) define('TABLE_ONLINE', 'Online');
if (!defined('TABLE_LEADER')) define('TABLE_LEADER', 'Leader');
if (!defined('TABLE_ADMIN')) define('TABLE_ADMIN', 'Admin');
if (!defined('TABLE_SKILL_M4')) define('TABLE_SKILL_M4', 'M4_Skill');
if (!defined('TABLE_SKILL_AK47')) define('TABLE_SKILL_AK47', 'AK47_Skill');
if (!defined('TABLE_SKILL_PISTOL')) define('TABLE_SKILL_PISTOL', 'Pistol_Skill');
if (!defined('TABLE_SKILL_SDPISTOL')) define('TABLE_SKILL_SDPISTOL', 'SDPistol_Skill');
if (!defined('TABLE_SKILL_DEAGLE')) define('TABLE_SKILL_DEAGLE', 'DesertEagle_Skill');
if (!defined('TABLE_SKILL_SHOTGUN')) define('TABLE_SKILL_SHOTGUN', 'ShotGun_Skill');
if (!defined('TABLE_SKILL_MP5')) define('TABLE_SKILL_MP5', 'MP5_Skill');
if (!defined('TABLE_SKILL_SNIPER')) define('TABLE_SKILL_SNIPER', 'SniperRifle_Skill');

$ucp_table_settings = array(
	//База 
	'table' => TABLE_ACCOUNTS,
	'id' => TABLE_ID,
	'name' => TABLE_NAME,
	'pass' => TABLE_PASSWORD,
	'cash' => TABLE_MONEY,
	'last_date' => TABLE_LASTDATE,
	'last_ip' => TABLE_LASTIP,
	'u_phone' => TABLE_PHONE,
	'biz' => TABLE_BUSINESS,
	'house' => TABLE_HOUSE,
	'level' => TABLE_LEVEL,  
	'bank' => TABLE_BANK, 
	'member' => TABLE_MEMBER, 
	'rank' => TABLE_RANK, 
	'job' => TABLE_JOB, 
	'warn' => TABLE_WARN,  
	'donate' => TABLE_DONATE, 
	'skin' => TABLE_SKIN, 
	'online' => TABLE_ONLINE, 
	'leader' => TABLE_LEADER,
	'admin' => TABLE_ADMIN,
	'Skill_M4' => TABLE_SKILL_M4,
	'Skill_AK47' => TABLE_SKILL_AK47,
	'Skill_Pistol' => TABLE_SKILL_PISTOL,
	'Skill_SDPistol' => TABLE_SKILL_SDPISTOL,
	'Skill_Deagle' => TABLE_SKILL_DEAGLE,
	'Skill_ShotGun' => TABLE_SKILL_SHOTGUN,
	'Skill_MP5' => TABLE_SKILL_MP5,
	'Skill_Sniper' => TABLE_SKILL_SNIPER,
);
$vehiclename = array(
	'400' => 'Landstalker',
	'401' => 'Bravura',
	'402' => 'Buffalo',
	'403' => 'Linerunner',
	'404' => 'Perenail',
	'405' => 'Sentinel',
	'406' => 'Dumper',
	'407' => 'Firetruck',
	'408' => 'Trashmaster',
	'409' => 'Stretch',
	'410' => 'Manana',
	'411' => 'Infernus',
	'412' => 'Voodoo',
	'413' => 'Pony',
	'414' => 'Mule',
	'415' => 'Cheetah',
	'416' => 'Ambulance',
	'417' => 'Levetian',
	'418' => 'Moonbeam',
	'419' => 'Esperanto',
	'420' => 'Taxi',
	'421' => 'Washington',
	'422' => 'Bobcat',
	'423' => 'Mr Whoopee',
	'424' => 'BF Injection',
	'425' => 'Hunter',
	'426' => 'Premier',
	'427' => 'Enforcer',
	'428' => 'Securicar',
	'429' => 'Banshee',
	'430' => 'Predator',
	'431' => 'Bus',
	'432' => 'Rhino',
	'433' => 'Barracks',
	'434' => 'Hotknife',
	'435' => 'Artic trailer 1',
	'436' => 'Previon',
	'437' => 'Coach',
	'438' => 'Cabbie',
	'439' => 'Stallion',
	'440' => 'Rumpo',
	'441' => 'RC Bandit',
	'442' => 'Romero',
	'443' => 'Packer',
	'444' => 'Monster',
	'445' => 'Admiral',
	'446' => 'Squalo',
	'447' => 'Seasparrow',
	'448' => 'Pizza boy',
	'449' => 'Tram',
	'450' => 'Artic trailer 2',
	'451' => 'Turismo',
	'452' => 'Speeder',
	'453' => 'Reefer',
	'454' => 'Tropic',
	'455' => 'Flatbed',
	'456' => 'Yankee',
	'457' => 'Caddy',
	'458' => 'Solair',
	'459' => 'Top fun',
	'460' => 'Skimmer',
	'461' => 'PCJ 600',
	'462' => 'Faggio',
	'463' => 'Freeway',
	'464' => 'RC Baron',
	'465' => 'RC Raider',
	'466' => 'Glendale',
	'467' => 'Oceanic',
	'468' => 'Sanchez',
	'469' => 'Sparrow',
	'470' => 'Patriot',
	'471' => 'Quad',
	'472' => 'Coastgaurd',
	'473' => 'Dinghy',
	'474' => 'Hermes',
	'475' => 'Sabre',
	'476' => 'Rustler',
	'477' => 'ZR 350',
	'478' => 'Walton',
	'479' => 'Regina',
	'480' => 'Comet',
	'481' => 'BMX',
	'482' => 'Burrito',
	'483' => 'Camper',
	'484' => 'Marquis',
	'485' => 'Baggage',
	'486' => 'Dozer',
	'487' => 'Maverick',
	'488' => 'VCN Maverick',
	'489' => 'Rancher',
	'490' => 'FBI Rancher',
	'491' => 'Virgo',
	'492' => 'Greenwood',
	'493' => 'Jetmax',
	'494' => 'Hotring',
	'495' => 'Sandking',
	'496' => 'Blistac',
	'497' => 'Police maverick',
	'498' => 'Boxville',
	'499' => 'Benson',
	'500' => 'Mesa',
	'501' => 'RC Goblin',
	'502' => 'Hotring A',
	'503' => 'Hotring B',
	'504' => 'Blood ring banger',
	'505' => 'Rancher (lure)',
	'506' => 'Super GT',
	'507' => 'Elegant',
	'508' => 'Journey',
	'509' => 'Bike',
	'510' => 'Mountain bike',
	'511' => 'Beagle',
	'512' => 'Cropduster',
	'513' => 'Stuntplane',
	'514' => 'Petrol',
	'515' => 'Roadtrain',
	'516' => 'Nebula',
	'517' => 'Majestic',
	'518' => 'Buccaneer',
	'519' => 'Shamal',
	'520' => 'Hydra',
	'521' => 'FCR 900',
	'522' => 'NRG 500',
	'523' => 'HPV 1000',
	'524' => 'Cement',
	'525' => 'Towtruck',
	'526' => 'Fortune',
	'527' => 'Cadrona',
	'528' => 'FBI Truck',
	'529' => 'Williard',
	'530' => 'Fork lift',
	'531' => 'Tractor',
	'532' => 'Combine',
	'533' => 'Feltzer',
	'534' => 'Remington',
	'535' => 'Slamvan',
	'536' => 'Blade',
	'537' => 'Freight',
	'538' => 'Streak',
	'539' => 'Vortex',
	'540' => 'Vincent',
	'541' => 'Bullet',
	'542' => 'Clover',
	'543' => 'Sadler',
	'544' => 'Firetruck LA',
	'545' => 'Hustler',
	'546' => 'Intruder',
	'547' => 'Primo',
	'548' => 'Cargobob',
	'549' => 'Tampa',
	'550' => 'Sunrise',
	'551' => 'Merit',
	'552' => 'Utility van',
	'553' => 'Nevada',
	'554' => 'Yosemite',
	'555' => 'Windsor',
	'556' => 'Monster A',
	'557' => 'Monster B',
	'558' => 'Uranus',
	'559' => 'Jester',
	'560' => 'Sultan',
	'561' => 'Stratum',
	'562' => 'Elegy',
	'563' => 'Raindance',
	'564' => 'RC Tiger',
	'565' => 'Flash',
	'566' => 'Tahoma',
	'567' => 'Savanna',
	'568' => 'Bandito',
	'569' => 'Freight flat',
	'570' => 'Streak',
	'571' => 'Kart',
	'572' => 'Mower',
	'573' => 'Duneride',
	'574' => 'Sweeper',
	'575' => 'Broadway',
	'576' => 'Tornado',
	'577' => 'AT 400',
	'578' => 'DFT 30',
	'579' => 'Huntley',
	'580' => 'Stafford',
	'581' => 'BF 400',
	'582' => 'News van',
	'583' => 'Tug',
	'584' => 'Petrol tanker',
	'585' => 'Emperor',
	'586' => 'Wayfarer',
	'587' => 'Euros',
	'588' => 'Hotdog',
	'589' => 'Club',
	'590' => 'Freight box',
	'591' => 'Artic trailer 3',
	'592' => 'Andromada',
	'593' => 'Dodo',
	'594' => 'RC Cam',
	'595' => 'Launch',
	'596' => 'Cop car LS',
	'597' => 'Cop car SF',
	'598' => 'Cop car LV',
	'599' => 'Ranger',
	'600' => 'Picador',
	'601' => 'Swat tank',
	'602' => 'Alpha',
	'603' => 'Phoenix',
	'604' => 'Glendale',
	'605' => 'Sadler',
	'606' => 'Bag box A',
	'607' => 'Bag box B',
	'608' => 'Stairs',
	'609' => 'Boxville (black)',
	'610' => 'Farm trailer',
	'611' => 'Utility van trailer',
);
?>